services:
  web:
    build: ./web
    restart: unless-stopped
    env_file:
      - ./web/.env
    ports:
      - "5173:80"
    networks:
      - network
  unity:
    build: ./web/unity
    restart: unless-stopped
    ports:
      - "5174:80"
    networks:
      - network
  api:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - network

networks:
  network:
