/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as AlgorithmRouteImport } from './routes/algorithm'
import { Route as SidebarRouteRouteImport } from './routes/_sidebar/route'
import { Route as SidebarChallengeRouteImport } from './routes/_sidebar/challenge'

const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmRoute = AlgorithmRouteImport.update({
  id: '/algorithm',
  path: '/algorithm',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarChallengeRoute = SidebarChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarRouteRouteWithChildren
  '/algorithm': typeof AlgorithmRoute
  '/knowledge': typeof KnowledgeRoute
  '/challenge': typeof SidebarChallengeRoute
}
export interface FileRoutesByTo {
  '/': typeof SidebarRouteRouteWithChildren
  '/algorithm': typeof AlgorithmRoute
  '/knowledge': typeof KnowledgeRoute
  '/challenge': typeof SidebarChallengeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/algorithm': typeof AlgorithmRoute
  '/knowledge': typeof KnowledgeRoute
  '/_sidebar/challenge': typeof SidebarChallengeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/algorithm' | '/knowledge' | '/challenge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/algorithm' | '/knowledge' | '/challenge'
  id:
    | '__root__'
    | '/_sidebar'
    | '/algorithm'
    | '/knowledge'
    | '/_sidebar/challenge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
  AlgorithmRoute: typeof AlgorithmRoute
  KnowledgeRoute: typeof KnowledgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithm': {
      id: '/algorithm'
      path: '/algorithm'
      fullPath: '/algorithm'
      preLoaderRoute: typeof AlgorithmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/challenge': {
      id: '/_sidebar/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof SidebarChallengeRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarChallengeRoute: typeof SidebarChallengeRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarChallengeRoute: SidebarChallengeRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
  AlgorithmRoute: AlgorithmRoute,
  KnowledgeRoute: KnowledgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
