// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/categories": {
            "post": {
                "description": "Creates a new course category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course-categories"
                ],
                "summary": "Create course category",
                "parameters": [
                    {
                        "description": "Category payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.InsertCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/categories/{id}": {
            "put": {
                "description": "Updates category by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course-categories"
                ],
                "summary": "Update course category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Category payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.UpdateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes category by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course-categories"
                ],
                "summary": "Delete course category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/courses": {
            "post": {
                "description": "Creates a new course with image, category and level",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "Create course",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Course title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course description",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Course category ID",
                        "name": "categoryId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course level: beginner|intermediate|advanced",
                        "name": "level",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Course hours",
                        "name": "hours",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Course image",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/courses/{id}": {
            "put": {
                "description": "Updates existing course",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "Update course",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course title",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course description",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Course category ID",
                        "name": "categoryId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Course level: beginner|intermediate|advanced",
                        "name": "level",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Course hours",
                        "name": "hours",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Course image",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes course by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "Delete course",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/courses/{id}/lessons": {
            "post": {
                "description": "Creates lesson for selected course",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "Create lesson in course",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Lesson payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.CreateLessonRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/is-admin": {
            "get": {
                "description": "Checks role (protected endpoint)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Check role",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerSuccessResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Logout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Exit",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerSuccessResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Update tokens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/sign-in": {
            "post": {
                "description": "User login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/sign-up": {
            "post": {
                "description": "Student signs up without code. Parent signs up with studentCode.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registration",
                "parameters": [
                    {
                        "description": "Sign up payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "Returns all course categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course-categories"
                ],
                "summary": "List course categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "get": {
                "description": "Returns a category by its id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "course-categories"
                ],
                "summary": "Get course category by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/courses": {
            "get": {
                "description": "Returns all courses",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "List courses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/courses/{id}": {
            "get": {
                "description": "Returns course detail by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "Get course by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/courses/{id}/lessons": {
            "get": {
                "description": "Returns ordered lessons for course",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "courses"
                ],
                "summary": "List course lessons",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Course ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/categories": {
            "get": {
                "description": "Returns a list of forum categories",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forum"
                ],
                "summary": "Get forum categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumCategoryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/comments/{id}/solution": {
            "put": {
                "description": "Marks a specific comment as the solution to the topic (only topic author can do this)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forum"
                ],
                "summary": "Mark comment as solution",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Topic ID",
                        "name": "topicId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/topics": {
            "get": {
                "description": "Returns a list of forum topics. Can be filtered by categoryId.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forum"
                ],
                "summary": "Get forum topics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "categoryId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumTopicResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new forum topic",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forum"
                ],
                "summary": "Create topic",
                "parameters": [
                    {
                        "description": "Topic data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.CreateForumTopicRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumTopicResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/topics/{id}": {
            "get": {
                "description": "Returns topic details along with comments",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forum"
                ],
                "summary": "Get topic details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Topic ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumTopicDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/topics/{id}/comments": {
            "post": {
                "description": "Creates a new comment in a topic",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "forum"
                ],
                "summary": "Create comment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Topic ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Comment data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.CreateForumCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumCommentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "description": "Returns current authenticated user with role name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/avatar": {
            "post": {
                "description": "Upload user avatar to S3",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Upload avatar",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Avatar file",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/parent/child-progress": {
            "get": {
                "description": "Returns current child progress for authenticated parent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Parent child progress",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ParentChildProgressResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "description": "Получение профиля текущего пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerErrorResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "status": {
                    "type": "boolean"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.AuthSwaggerSuccessResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "status": {
                    "type": "boolean"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.CreateForumCommentRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Вот решение вашей проблемы..."
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.CreateForumTopicRequest": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "type": "integer",
                    "example": 1
                },
                "content": {
                    "type": "string",
                    "example": "У меня вопрос по связям..."
                },
                "title": {
                    "type": "string",
                    "example": "Как использовать GORM?"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.CreateLessonRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "First lesson of the course"
                },
                "estimatedMinutes": {
                    "type": "integer",
                    "example": 25
                },
                "isFreePreview": {
                    "type": "boolean",
                    "example": true
                },
                "order": {
                    "type": "integer",
                    "example": 1
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.CreateLessonTaskRequest"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Intro to Python"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.CreateLessonTaskRequest": {
            "type": "object",
            "properties": {
                "correctOptionIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "Проверьте понимание темы"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.CreateTaskOptionRequest"
                    }
                },
                "question": {
                    "type": "string",
                    "example": "Какие варианты верные?"
                },
                "title": {
                    "type": "string",
                    "example": "Базовый тест"
                },
                "type": {
                    "type": "string",
                    "example": "quiz"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.CreateTaskOptionRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "a"
                },
                "text": {
                    "type": "string",
                    "example": "Ответ A"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Описание ошибки"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumAuthor": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "stars": {
                    "type": "integer"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumCategoryResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "topicsCount": {
                    "type": "integer"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumCommentResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumAuthor"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isSolution": {
                    "type": "boolean"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumTopicDetailResponse": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumCommentResponse"
                    }
                },
                "topic": {
                    "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumTopicResponse"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumTopicResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ForumAuthor"
                },
                "categoryId": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isSolved": {
                    "type": "boolean"
                },
                "replies": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "views": {
                    "type": "integer"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.InsertCategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Название категории",
                    "type": "string",
                    "example": "Веб-разработка"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.MeResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "https://minio.local/avatar_1.png"
                },
                "exp": {
                    "type": "integer",
                    "example": 45
                },
                "expToNextLevel": {
                    "type": "integer",
                    "example": 55
                },
                "fullName": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "level": {
                    "type": "integer",
                    "example": 1
                },
                "login": {
                    "type": "string",
                    "example": "teacher01"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "+79001234567"
                },
                "roleId": {
                    "type": "integer",
                    "example": 2
                },
                "roleName": {
                    "type": "string",
                    "example": "student"
                },
                "stars": {
                    "type": "integer",
                    "example": 10
                },
                "streak": {
                    "type": "integer",
                    "example": 4
                },
                "studentCode": {
                    "type": "string",
                    "example": "STU-8A7KQ21M"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.ParentChildProgressResponse": {
            "type": "object",
            "properties": {
                "achievements": {
                    "type": "integer",
                    "example": 4
                },
                "exp": {
                    "type": "integer",
                    "example": 45
                },
                "level": {
                    "type": "integer",
                    "example": 1
                },
                "stars": {
                    "type": "integer",
                    "example": 18
                },
                "studentCode": {
                    "type": "string",
                    "example": "STU-8A7KQ21M"
                },
                "studentId": {
                    "type": "integer",
                    "example": 12
                },
                "studentLogin": {
                    "type": "string",
                    "example": "petya_ivanov"
                },
                "studentName": {
                    "type": "string",
                    "example": "Petya Ivanov"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SignInRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SignUpRequest": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "studentCode": {
                    "type": "string"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "Операция выполнена успешно"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.UpdateCategoryRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Новое название категории",
                    "type": "string",
                    "example": "Frontend разработка"
                }
            }
        },
        "github_com_FantomStudy_fluffy-doodle_internal_api_presenter.UserProfileResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "https://minio.local/avatar_1.png"
                },
                "exp": {
                    "type": "integer",
                    "example": 45
                },
                "expToNextLevel": {
                    "type": "integer",
                    "example": 55
                },
                "fullName": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "level": {
                    "type": "integer",
                    "example": 1
                },
                "login": {
                    "type": "string",
                    "example": "teacher01"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "+79001234567"
                },
                "roleId": {
                    "type": "integer",
                    "example": 2
                },
                "stars": {
                    "type": "integer",
                    "example": 10
                },
                "streak": {
                    "type": "integer",
                    "example": 4
                },
                "studentCode": {
                    "type": "string",
                    "example": "STU-8A7KQ21M"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Fluffy Doodle REST API",
	Description:      "This is Rest Api for Fluffy Doodle",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
