basePath: /
definitions:
  presenter.AuthSwaggerErrorResponse:
    properties:
      error: {}
      status:
        type: boolean
    type: object
  presenter.AuthSwaggerSuccessResponse:
    properties:
      error: {}
      status:
        type: boolean
    type: object
  presenter.ErrorResponse:
    properties:
      error:
        example: Описание ошибки
        type: string
      success:
        example: false
        type: boolean
    type: object
  presenter.InsertCategoryRequest:
    properties:
      name:
        description: Название категории
        example: Веб-разработка
        type: string
    required:
    - name
    type: object
  presenter.SignInRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  presenter.SignUpRequest:
    properties:
      fullName:
        type: string
      login:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
    type: object
  presenter.SuccessResponse:
    properties:
      data: {}
      message:
        example: Операция выполнена успешно
        type: string
      success:
        example: true
        type: boolean
    type: object
  presenter.UpdateCategoryRequest:
    properties:
      name:
        description: Новое название категории
        example: Frontend разработка
        type: string
    required:
    - name
    type: object
  github_com_FantomStudy_fluffy-doodle_internal_models.Achievement:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  github_com_FantomStudy_fluffy-doodle_internal_models.Role:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
      users:
        items:
          $ref: '#/definitions/github_com_FantomStudy_fluffy-doodle_internal_models.User'
        type: array
    type: object
  github_com_FantomStudy_fluffy-doodle_internal_models.User:
    properties:
      achievements:
        description: Достижения
        items:
          $ref: '#/definitions/github_com_FantomStudy_fluffy-doodle_internal_models.Achievement'
        type: array
      avatar:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      fullName:
        type: string
      id:
        type: integer
      login:
        type: string
      phoneNumber:
        type: string
      role:
        $ref: '#/definitions/github_com_FantomStudy_fluffy-doodle_internal_models.Role'
      roleId:
        description: Роль
        type: integer
      stars:
        type: integer
      updatedAt:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object

host: localhost:3000
info:
  contact: {}
  description: This is Rest Api for Fluffy Doodle
  termsOfService: http://swagger.io/terms/
  title: Fluffy Doodle REST API
  version: "1.0"

paths:
  /admin/categories:
    post:
      consumes:
      - application/json
      description: Creates a new course category
      parameters:
      - description: Category payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/presenter.InsertCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/presenter.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: Create course category
      tags:
      - course-categories

  /admin/categories/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes category by id
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: Delete course category
      tags:
      - course-categories

    put:
      consumes:
      - application/json
      description: Updates category by id
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/presenter.UpdateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: Update course category
      tags:
      - course-categories

  /auth/is-admin:
    get:
      consumes:
      - application/json
      description: Проверяет пользователя на роль администратора
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerSuccessResponse'
      summary: Check role
      tags:
      - auth

  /auth/logout:
    post:
      consumes:
      - application/json
      description: Выход пользователя из системы
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerSuccessResponse'
      summary: Exit
      tags:
      - auth

  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Обновление токенов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
      summary: Update tokens
      tags:
      - auth

  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Авторизация пользователя
      parameters:
      - description: Данные для авторизации
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/presenter.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
      summary: Login
      tags:
      - auth

  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Регистрация пользователя
      parameters:
      - description: Данные для регистрации
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/presenter.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
      summary: Registration
      tags:
      - auth

  /categories:
    get:
      consumes:
      - application/json
      description: Returns all course categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: List course categories
      tags:
      - course-categories

  /categories/{id}:
    get:
      consumes:
      - application/json
      description: Returns a category by its id
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.ErrorResponse'
      summary: Get course category by id
      tags:
      - course-categories

  /user/avatar:
    post:
      consumes:
      - multipart/form-data
      description: Загрузка аватарки пользователя в S3
      parameters:
      - description: Файл аватарки
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
      summary: Upload avatar
      tags:
      - user

  /user/profile:
    get:
      description: Получение профиля текущего пользователя
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_FantomStudy_fluffy-doodle_internal_models.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
      summary: Get user profile
      tags:
      - user

  /user/student-invitation:
    post:
      consumes:
      - application/json
      description: Регистрация студента
      parameters:
      - description: Данные для регистрации ученика
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/presenter.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenter.AuthSwaggerErrorResponse'
      summary: Invite student
      tags:
      - user

swagger: "2.0"
