/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarRouteRouteImport } from './routes/_sidebar/route'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as SidebarIndexRouteImport } from './routes/_sidebar/index'
import { Route as SidebarKnowledgeRouteImport } from './routes/_sidebar/knowledge'
import { Route as SidebarCourseRouteImport } from './routes/_sidebar/course'
import { Route as SidebarChallengeRouteImport } from './routes/_sidebar/challenge'
import { Route as SidebarAlgorithmRouteImport } from './routes/_sidebar/algorithm'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarIndexRoute = SidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarKnowledgeRoute = SidebarKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarCourseRoute = SidebarCourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarChallengeRoute = SidebarChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAlgorithmRoute = SidebarAlgorithmRouteImport.update({
  id: '/algorithm',
  path: '/algorithm',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarIndexRoute
  '/algorithm': typeof SidebarAlgorithmRoute
  '/challenge': typeof SidebarChallengeRoute
  '/course': typeof SidebarCourseRoute
  '/knowledge': typeof SidebarKnowledgeRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/algorithm': typeof SidebarAlgorithmRoute
  '/challenge': typeof SidebarChallengeRoute
  '/course': typeof SidebarCourseRoute
  '/knowledge': typeof SidebarKnowledgeRoute
  '/': typeof SidebarIndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/algorithm': typeof SidebarAlgorithmRoute
  '/_sidebar/challenge': typeof SidebarChallengeRoute
  '/_sidebar/course': typeof SidebarCourseRoute
  '/_sidebar/knowledge': typeof SidebarKnowledgeRoute
  '/_sidebar/': typeof SidebarIndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algorithm'
    | '/challenge'
    | '/course'
    | '/knowledge'
    | '/login/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/algorithm'
    | '/challenge'
    | '/course'
    | '/knowledge'
    | '/'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/_sidebar'
    | '/_sidebar/algorithm'
    | '/_sidebar/challenge'
    | '/_sidebar/course'
    | '/_sidebar/knowledge'
    | '/_sidebar/'
    | '/login/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/': {
      id: '/_sidebar/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarIndexRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/knowledge': {
      id: '/_sidebar/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof SidebarKnowledgeRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/course': {
      id: '/_sidebar/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof SidebarCourseRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/challenge': {
      id: '/_sidebar/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof SidebarChallengeRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/algorithm': {
      id: '/_sidebar/algorithm'
      path: '/algorithm'
      fullPath: '/algorithm'
      preLoaderRoute: typeof SidebarAlgorithmRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarAlgorithmRoute: typeof SidebarAlgorithmRoute
  SidebarChallengeRoute: typeof SidebarChallengeRoute
  SidebarCourseRoute: typeof SidebarCourseRoute
  SidebarKnowledgeRoute: typeof SidebarKnowledgeRoute
  SidebarIndexRoute: typeof SidebarIndexRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarAlgorithmRoute: SidebarAlgorithmRoute,
  SidebarChallengeRoute: SidebarChallengeRoute,
  SidebarCourseRoute: SidebarCourseRoute,
  SidebarKnowledgeRoute: SidebarKnowledgeRoute,
  SidebarIndexRoute: SidebarIndexRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
