/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarRouteRouteImport } from './routes/_sidebar/route'
import { Route as SidebarKnowledgeRouteImport } from './routes/_sidebar/knowledge'
import { Route as SidebarChallengeRouteImport } from './routes/_sidebar/challenge'
import { Route as SidebarAlgorithmRouteImport } from './routes/_sidebar/algorithm'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarKnowledgeRoute = SidebarKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarChallengeRoute = SidebarChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAlgorithmRoute = SidebarAlgorithmRouteImport.update({
  id: '/algorithm',
  path: '/algorithm',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarRouteRouteWithChildren
  '/algorithm': typeof SidebarAlgorithmRoute
  '/challenge': typeof SidebarChallengeRoute
  '/knowledge': typeof SidebarKnowledgeRoute
}
export interface FileRoutesByTo {
  '/': typeof SidebarRouteRouteWithChildren
  '/algorithm': typeof SidebarAlgorithmRoute
  '/challenge': typeof SidebarChallengeRoute
  '/knowledge': typeof SidebarKnowledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/algorithm': typeof SidebarAlgorithmRoute
  '/_sidebar/challenge': typeof SidebarChallengeRoute
  '/_sidebar/knowledge': typeof SidebarKnowledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/algorithm' | '/challenge' | '/knowledge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/algorithm' | '/challenge' | '/knowledge'
  id:
    | '__root__'
    | '/_sidebar'
    | '/_sidebar/algorithm'
    | '/_sidebar/challenge'
    | '/_sidebar/knowledge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/knowledge': {
      id: '/_sidebar/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof SidebarKnowledgeRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/challenge': {
      id: '/_sidebar/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof SidebarChallengeRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/algorithm': {
      id: '/_sidebar/algorithm'
      path: '/algorithm'
      fullPath: '/algorithm'
      preLoaderRoute: typeof SidebarAlgorithmRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarAlgorithmRoute: typeof SidebarAlgorithmRoute
  SidebarChallengeRoute: typeof SidebarChallengeRoute
  SidebarKnowledgeRoute: typeof SidebarKnowledgeRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarAlgorithmRoute: SidebarAlgorithmRoute,
  SidebarChallengeRoute: SidebarChallengeRoute,
  SidebarKnowledgeRoute: SidebarKnowledgeRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
